flare:
  fhir:
    server: 'http://localhost:8082/fhir'
    user: ''
    password: ''
    pageCount: 1000
  cache:
    memSizeMB: 1024
    memExpiryHours: 48
    memRefreshHours: 24
    diskPath: 'cache'
    diskExpiryHours: 168
  mapping:
    mappingsFile: 'ontology/codex-term-code-mapping.json'
    conceptTreeFile: 'ontology/codex-code-tree.json'

server:
  port: 8080
